### ISSUE TITLE
Create tag 0.0.1

### ISSUE THREAD

**Issue by dingwilson** [ShawnMoore/XMLParsing#14]
Thanks for merging my PR! 👍 For CocoaPods to work, there needs to be a tag to clone. Please create a tag `0.0.1`. Thanks!

PS: After doing so, please push the podspec. If you need help with that, feel free to let me know! I would be more than happy to help out in any way possible. :)

**Comment by dingwilson** [comment]
Hey all, to allow users to use the project, I have gone ahead and updated [my fork](https://github.com/dingwilson/XMLParsing), as well as published to cocoapods (0.0.2).

@ShawnMoore: if you are still active/interested in maintaining this project, I would be more than happy to transfer the CocoaPods ownership to you.

**Comment by stonedauwg** [comment]
Good job and thx @dingwilson

**Comment by MihaelIsaev** [comment]
SPM can use this lib directly from `master` branch without tagging

**Comment by dingwilson** [comment]
@MihaelIsaev good catch, I've updated my above comment! However, CocoaPods still requires that the branch be tagged.

**Comment by MihaelIsaev** [comment]
Cocoapods also can use libs directly from branches or even commits 
`:branch => 'master'`
`:commit => '0f506b1c45'`
🙂

**Comment by dingwilson** [comment]
Oh wow, learn something new everyday. I thought you had to push the podspec, but apparently not. Thanks! :)

**Comment by stonedauwg** [comment]
I believe Carthge DOES require a tag though, so still appreciated

**Comment by dingwilson** [comment]
Actually (although I've never personally tried this before), it seems that you can specify a specific commit hash or branch (`master`, or even `HEAD` if you're feeling dangerous) for Carthage.

**Comment by dingwilson** [comment]
Tag has been created... closing issue.
