### ISSUE TITLE
Encode attributes

### ISSUE THREAD

**Issue by MetaImi** [ShawnMoore/XMLParsing#17]
HI

I played with your library a bit, and it is really a great job! However there is a huge technical gap in the decoding part: We are losing the information that the property was an attribute or an element. For decoding it works well, but it can not save the information in the same way. 
Example:

```
struct Test {
var name: String?
var information: String?
}

Input: 
<test name="tag">
<information>tag information</information>
</test>

Output: 
<test>
<name>tag</name>
<information>tag information</information>
</test>
```

**Comment by stonedauwg** [comment]
Figured out a way to encode attributes. By default, it treats all Encodable props as XML elements. The  XMLEncoder.attributeEncodingStrategy property controls this. That enum is set to default (by default) but can be changed to custom, where you then provide a closure to control if a particular piece of data should be an attribute or not. =Return true from the closure to make it be an attribute. I have used it in a test app and works perfectly

**Comment by nacho4d** [comment]
@stonedauwg Can you show how did you use `XMLEncoder.attributeEncodingStrategy ` please? I am interested in this part too.

Also, I think an encoding example (with attributes) should be added to the README.md 👍

**Comment by regexident** [comment]
@nacho4d `attributeEncodingStrategy` has since been superseded by `nodeEncodingStrategy`. 

https://github.com/MaxDesiatov/XMLCoder/blob/master/Tests/XMLCoderTests/NodeEncodingStrategyTests.swift should give you an idea on how to use it for the time being.
