### ISSUE TITLE
How to decode empty array?

### ISSUE THREAD

**Issue by MihaelIsaev** [ShawnMoore/XMLParsing#21]
I have server response like this

    <?xml version="1.0" encoding="UTF-8"?>
    <add-ons type="array"/>

I'm trying to decode it as `[AddOn]`

```swift
public final class AddOn: BraintreeContent {
    public var amount: Double?
    public var currentBillingCycle: Int?
    public var description: String
}
```

but I'm getting error `DecodingError.keyNotFound: Value required for key 'Index 0.description'.`
Is there any way to decode it properly into empty array or this framework just doesn't support decoding empty arrays?

**Comment by ShawnMoore** [comment]
You should try to decode it as an ```[AddOn]?```. This will force the decoder to use ```decodeIfPresent``` that will return _nil_ if the key does not exist.

**Comment by MihaelIsaev** [comment]
I expect to get an empty array instead of nil

**Comment by MihaelIsaev** [comment]
@ShawnMoore 
> You should try to decode it as an `[AddOn]?`. This will force the decoder to use `decodeIfPresent` that will return _nil_ if the key does not exist.

I'm still getting `DecodingError.keyNotFound: Value required for key 'Index 0.description'.` even when I decoding it as `[AddOn]?`. Looks like it should be fixed
