### ISSUE TITLE
Parser is unable to parse continuous  set of String

### ISSUE THREAD

**Issue by remyarm** [ShawnMoore/XMLParsing#53]
Hi Team,

I am trying to parse below simple json file
 "<Value><Name>Public</Name><Name>LowRisk</Name><Name>MediumRisk</Name><Name>HighRisk</Name></Value>"
Below struct I have defined for it
struct Value: Decodable {
    var name: [String]?
    enum CodingKeys: String, CodingKey {
           case name = "Name"
       }
    public init(from decoder: Decoder) throws {
           let values = try decoder.container(keyedBy: CodingKeys.self)
           name = try? values.decode([String].self, forKey: .name)
       }
}

but the parser failed to decode the above xml file.

I have debugged the code and found out that node.flatten() code in line number 256 , in class _XMLStackParser is returning only final value from the child array. So ultimately I am getting value of last node

<Name>HighRisk</Name>

Please fix the issue as early as possible.

Thanks,
Remya.

**Comment by MaxDesiatov** [comment]
Hi Remya, thank you for reporting the issue. You've mentioned a JSON file above, but this library can't be used for parsing JSON. Also, as you've mentioned an XML file later, it's not possible to diagnose the issue without looking at the actual file, or at least an XML snippet that you're seeing the issue with. Would you be able to attach that XML to this issue?

**Comment by MaxDesiatov** [comment]
Also, the XMLParsing library hasn't been maintained for quite some time. I would suggest checking whether your code works with [XMLCoder](https://github.com/MaxDesiatov/XMLCoder) first, which maintains a very similar API, but is still maintained. If the issues is reproducible with XMLCoder too, I would be able to fix it there, but not in XMLParsing, to which I don't have commit access unfortunately.

**Comment by remyarm** [comment]
Thanks @MaxDesiatov  for quick response - I tried parsing XML file with [XMLCoder](https://github.com/MaxDesiatov/XMLCoder/) , and it is working fine there. Very advanced Library , Good Job ... Thanks...
